# Generated by Django 2.0 on 2019-04-13 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MarineAnimals', '0002_auto_20190413_0452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animals',
            old_name='body',
            new_name='content',
        ),
    ]
