# Generated by Django 2.0 on 2019-04-13 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MarineAnimals', '0003_auto_20190413_0502'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Animals',
            new_name='Animal',
        ),
    ]
